version: '2'

services:
    web:
        image: php:7.2-apache
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/html
        links:
            - db:db
    db:
        image: mariadb
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8090:80"
        links:
            - db:db

# docker-compose up -d
